[phases.setup]
nixPkgs = [
    "ffmpeg",
    "libxml2",
    "libxslt",
    "zlib",
    "gcc",
    "python39"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install wheel",
    "pip install -r requirements.txt --use-pep517"
]

[start]
cmd = "python3 -m bot"
